---
title: "EBOVAC - EDA"
output: html_notebook
---

```{r echo=FALSE, results='hide'}
# SETTINGS
rm(list = ls())
options(stringsAsFactors = F)
basedir <- '/media/marcon/storage/dataanalysis/isobel/ebola'

# LIBRARIES
pkgs <- c('tidyverse','burro','esquisse','Factoshiny')
sapply(pkgs, require, character.only = T)
```

Load data
```{r echo=FALSE, results='hide'}
# source(file.path(basedir,'src/helper/preprocessing_functions.R'))
# ebovacObj <- preprocess_ebovacRnaseq()
ebovacObj <- suppressMessages(
  readRDS(file.path(basedir,'intermediate/preprocessed_data/ebovac/ebovacObj.rds'))
)
```

EDA
```{r}
sampleinfo <- as.data.frame(colData(ebovacObj))

#--- BURRO
# explore_data(dataset = sampleinfo)

plot_outcomeByVar <- function(var_name = 'chills', 
                              outcome_var = 'artrithis',
                              data = sampleinfo) {
  data = data.frame(outcome = data[,outcome_var],var = data[,var_name])
  ggplot(data,aes(var, fill = outcome)) + geom_bar() + 
    geom_text(stat = 'count', 
              aes(label = paste0(round((..count../sum(..count..))*100,2))),
              vjust = -1, size = 3) +
    labs(x = var_name, y = outcome_var, 
         subtitle = paste0('% of ',outcome_var,' factors by ',var_name),
         fill = outcome_var) +
    theme_minimal() + theme(legend.position = 'top') + 
    scale_fill_manual(values = c('grey','darkred'))
}
```

## sanity-check
```{r}
# treatment x artriths
plot_outcomeByVar(var_name = 'treatment',outcome_var = 'artrithis')

# treatment x viremia
ggplot(sampleinfo, aes(treatment,viremia,color = treatment)) + 
  geom_point(size = 3,alpha = .6, show.legend = F) + theme_linedraw() + 
  theme(legend.position = 'top') + 
  scale_color_manual(values = c('black','darkred'))

# treatment x fever
ggplot(sampleinfo, aes(treatment,fever,color = treatment)) + 
  geom_point(size = 3,alpha = .6, show.legend = F) + theme_linedraw() + 
  theme(legend.position = 'top') + 
  scale_color_manual(values = c('black','darkred'))
```

## Variables w/ ~ balanced Artriths outcomes between groups:
```{r}
plot_outcomeByVar(var_name = 'dose')
plot_outcomeByVar(var_name = 'gender')
```

## var-specific
```{r}
plot_outcomeByVar(var_name = 'chills')
plot_outcomeByVar(var_name = 'library_batch')
plot_outcomeByVar(var_name = 'myalgia')
plot_outcomeByVar(var_name = 'obj_fever')
plot_outcomeByVar(var_name = 'pain')
plot_outcomeByVar(var_name = 'subj_fever')
plot_outcomeByVar(var_name = 'viremia_d1')
```

## TEST IF IT`S CORR:
```{r}
# treatment x mapped_reads
# age x subj_fever
# artriths x fever
# artriths x mapped_reads
# artriths x viremia
# viremia x chills
# chills x group_day
# chills x mapped_reads
# chills x sampling_day
# dose x mapped_reads
# gender x fever
# gender x mapped_reads
# gender x viremia
# myalgia x viremia
# myalgia x fever
# myalgia x age
# myalgia x mapped_reads
# viremia x obj_fever
# obj_fever x fever
# group_day x obj_fever
# viremia x obj_fever
# pain x viremia
# pain x fever
# pain x group_day
# pain x mapped_reads
```

